// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMW2Hxxmtdn3x41j_rdb8aBKwb9Q3PqXI',
    appId: '1:19464650652:web:4b172bb72366a21a671259',
    messagingSenderId: '19464650652',
    projectId: 'abc1224-ffab7',
    authDomain: 'abc1224-ffab7.firebaseapp.com',
    storageBucket: 'abc1224-ffab7.firebasestorage.app',
    measurementId: 'G-JMWGHB1YGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI4Qdg3Q1fDyc3uXlvYGshrC0lVAvtxm4',
    appId: '1:19464650652:android:af6e1105e1158b17671259',
    messagingSenderId: '19464650652',
    projectId: 'abc1224-ffab7',
    storageBucket: 'abc1224-ffab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQp6OJmH-JS0rFVwmVYoM340QsuVUQAU',
    appId: '1:19464650652:ios:6fa2a85a08123ef2671259',
    messagingSenderId: '19464650652',
    projectId: 'abc1224-ffab7',
    storageBucket: 'abc1224-ffab7.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFQp6OJmH-JS0rFVwmVYoM340QsuVUQAU',
    appId: '1:19464650652:ios:6fa2a85a08123ef2671259',
    messagingSenderId: '19464650652',
    projectId: 'abc1224-ffab7',
    storageBucket: 'abc1224-ffab7.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMW2Hxxmtdn3x41j_rdb8aBKwb9Q3PqXI',
    appId: '1:19464650652:web:f01f803e9a30cb2d671259',
    messagingSenderId: '19464650652',
    projectId: 'abc1224-ffab7',
    authDomain: 'abc1224-ffab7.firebaseapp.com',
    storageBucket: 'abc1224-ffab7.firebasestorage.app',
    measurementId: 'G-FF57FYGYHE',
  );
}
